---
name: CI
on:
  pull_request:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v7

      - name: Set up Python 3.
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.4.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Lint code.
        run: |
          source .venv/bin/activate
          ansible-lint defaults tasks meta molecule

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - image: ubuntu
            version: 22.04
          - image: debian
            version: 12.6
          - image: rockylinux
            version: 9.3
          - image: fedora
            version: 39

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v7

      - name: Set up Python 3.
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.4.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run Molecule tests.
        run: |
          source .venv/bin/activate
          molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro.image }}
          MOLECULE_DISTRO_VER: ${{ matrix.distro.version }}
