name: Test

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:3.11.5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: pip install -r requirements.txt
      - run: ansible-lint defaults tasks
